name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVEUR_POKEMON_MATHYS }}

      - name: Add remote server to known_hosts
        run: ssh-keyscan -H 151.80.58.182 >> ~/.ssh/known_hosts

      - name: List files on remote server
        run: ssh debian@151.80.58.182 "echo 'Hello, World!' > ~/test_file.txt"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Clear temporary folder on remote server
        run: |
          ssh debian@151.80.58.182 "rm -rf /var/www/mathys/*"
          echo "Dossier temporaire vidé avec succès."

      - name: Deploy files to remote server via SCP
        run: |
          scp -r dist/* debian@151.80.58.182:/var/www/mathys
          echo "Fichiers copiés avec succès."

      - name: Message de fin
        run: echo "🎉 Déploiement réussi !"
